New Log Issue Command

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -199,7 +199,11 @@ stages:
         echo This is the first step
       displayName: First Step
     - script: |
-        #!/bin/bash
         echo "##vso[task.logissue type=error]Something went very wrong."
         echo "Check if this is printed"
       displayName: Log Issue Command
+    - script: |
+        echo "##vso[task.logissue type=error]Something went very wrong."
+        exit 1
+        echo "Check if this is printed"
+      displayName: Log Issue Command 2
